// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlfnk9qkgnZbNVjiFa8LMy1I_p5dDeNZo',
    appId: '1:42838233391:web:8ec34e34c378b139e551da',
    messagingSenderId: '42838233391',
    projectId: 'gsworldcenter9',
    authDomain: 'gsworldcenter9.firebaseapp.com',
    storageBucket: 'gsworldcenter9.firebasestorage.app',
    measurementId: 'G-64TZMYPPW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkoKSgPmUhbzklQkViyMr-GjsOV7pUnRY',
    appId: '1:42838233391:android:76b7a388e543af98e551da',
    messagingSenderId: '42838233391',
    projectId: 'gsworldcenter9',
    storageBucket: 'gsworldcenter9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPB_675OMIkRci2nal3cycFatqtLmtSBM',
    appId: '1:42838233391:ios:740e23acbbcfc823e551da',
    messagingSenderId: '42838233391',
    projectId: 'gsworldcenter9',
    storageBucket: 'gsworldcenter9.firebasestorage.app',
    iosBundleId: 'com.example.gsWorldCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPB_675OMIkRci2nal3cycFatqtLmtSBM',
    appId: '1:42838233391:ios:740e23acbbcfc823e551da',
    messagingSenderId: '42838233391',
    projectId: 'gsworldcenter9',
    storageBucket: 'gsworldcenter9.firebasestorage.app',
    iosBundleId: 'com.example.gsWorldCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlfnk9qkgnZbNVjiFa8LMy1I_p5dDeNZo',
    appId: '1:42838233391:web:81802c619de03cdce551da',
    messagingSenderId: '42838233391',
    projectId: 'gsworldcenter9',
    authDomain: 'gsworldcenter9.firebaseapp.com',
    storageBucket: 'gsworldcenter9.firebasestorage.app',
    measurementId: 'G-B9E4JZX2X0',
  );
}
